# Generated by Django 4.1 on 2023-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosede', '0002_wine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerveja_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whisky_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
